apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
  namespace: {{ .Values.environment }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  type: {{ .Values.frontend.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.deploymentPort }}