apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.mongo.name }}-service
  namespace: {{ .Values.environment }}
spec:
  selector:
      app: {{ .Values.mongo.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.servicePort }}
      targetPort: {{ .Values.mongo.deploymentPort }}
  type: {{ .Values.mongo.type }}
