apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: denyshabouev/cloud-infra-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
          